---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  provider: lxc

platforms:
- name: ubuntu-13.04
  driver_config:
    box: vagrant-lxc-raring64-2013-09-28
    box_url: http://bit.ly/vagrant-lxc-raring64-2013-09-28-
- name: ubuntu-12.04
  driver_config:
    box: vagrant-lxc-precise64-2013-09-28
    box_url: http://bit.ly/vagrant-lxc-precise64-2013-09-28
#- name: ubuntu-10.04
#  driver_config:
#    box: opscode-ubuntu-10.04
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
## Waiting for http://tickets.opscode.com/browse/CHEF-4125
#- name: debian-7.1.0
#  driver_config:
#    box: opscode-debian-7.1.0
#    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
#- name: debian-6
#  driver_config:
#    box: puppetlabs-debian-6
#    box_url: http://puppet-vagrant-boxes.puppetlabs.com/debian-607-x64-vbox4210-nocm.box

suites:
- name: server
  run_list:
    - recipe[icinga-test-helper]
    - recipe[icinga::server]
  attributes:
    nagios:
      server_auth_method: htauth
