---
#driver_plugin: vagrant
driver_plugin: lxc
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu_1204
  driver_config:
    base_container: ubuntu_1204 # your base container name
    username: ubuntu # defaults to "root"
    password: ubuntu # defaults to "root"
- name: ubuntu_1304
  driver_config:
    base_container: ubuntu_1304
    username: ubuntu
    password: ubuntu
## Needs a fix for dhclient not sending hostname to dnsmasq
#- name: debian-6
#  driver_config:
#    base_container: debian_6
#    username: kitchen
#    password: kitchen
- name: ubuntu-10.04
  driver_config:
    base_container: ubuntu_1004
    username: ubuntu
    password: ubuntu

## Waiting for http://tickets.opscode.com/browse/CHEF-4125
## Needs to be created yet
#- name: debian-7.1.0
#  driver_config:
#    base_container: debian_71
#    username: kitchen
#    password: kitchen
suites:
- name: server
  run_list:
    - recipe[icinga-test-helper]
    - recipe[icinga::server]
  attributes:
    nagios:
      server_auth_method: htauth
